<a href="https://colab.research.google.com/github/JoseMartin2004/tecnovationPt/blob/main/Arquivo_Inicial_Minicurso_Analise_de_Dados_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Desafio:

Você trabalha em uma grande empresa de Cartão de Crédito e o diretor da empresa percebeu que o número de clientes que cancelam seus cartões tem aumentado significativamente, causando prejuízos enormes para a empresa

O que fazer para evitar isso? Como saber as pessoas que têm maior tendência a cancelar o cartão?

# O que temos:

Temos 1 base de dados com informações dos clientes, tanto clientes atuais quanto clientes que cancelaram o cartão

Download da Base de Dados: Botão na página

Referência: https://www.kaggle.com/sakshigoyal7/credit-card-customers

1 - importar DB
2 - Organizar DB
3 - Analizar DB
4 - Relatar o problema

objetivo: Identificar as causas do problema para propormos possível solução.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [7]:
import pandas as pd

tabela =pd.read_csv("/content/drive/MyDrive/MinicursoColab/ClientesBanco.csv", encoding="latin1")
tabela = tabela.dropna()
display(tabela.info())

<class 'pandas.core.frame.DataFrame'>
Index: 10126 entries, 0 to 10126
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   CLIENTNUM                      10126 non-null  int64
 1   Categoria                      10126 non-null  object
 2   Idade                          10126 non-null  int64
 3   Sexo                           10126 non-null  object
 4   Dependentes                    10126 non-null  int64
 5   Educação                       10126 non-null  object
 6   Estado Civil                   10126 non-null  object
 7   Faixa Salarial Anual           10126 non-null  object
 8   Categoria Cartão               10126 non-null  object
 9   Meses como Cliente             10126 non-null  int64
 10  Produtos Contratados           10126 non-null  int64
 11  Inatividade 12m                10126 non-null  int64
 12  Contatos 12m                   10126 non-null  int64
 13  Limite                         10126 non-null  float64
 14  Limite Consumido               10126 non-null  int64
 15  Limite Disponível              10126 non-null  float64
 16  Mudanças Transacoes_Q4_Q1      10126 non-null  float64
 17  Valor Transacoes 12m           10126 non-null  int64
 18  Qtde Transacoes 12m            10126 non-null  int64
 19  Mudança Qtde Transações_Q4_Q1  10126 non-null  float64
 20  Taxa de Utilização Cartão      10126 non-null  float64
dtypes: float64(5), int64(10), object(6)
memory usage: 1.7+ MB

None

In [8]:
display(tabela.describe())

,CLIENTNUM,Idade,Dependentes,Meses como Cliente,Produtos Contratados,Inatividade 12m,Contatos 12m,Limite,Limite Consumido,Limite Disponível,Mudanças Transacoes_Q4_Q1,Valor Transacoes 12m,Qtde Transacoes 12m,Mudança Qtde Transações_Q4_Q1,Taxa de Utilização Cartão
count,1.012600e+04,10126.000000,10126.000000,10126.000000,10126.000000,10126.000000,10126.000000,10126.000000,10126.000000,10126.000000,10126.000000,10126.000000,10126.000000,10126.000000,10126.000000
mean,7.391700e+08,46.327079,2.346139,35.928995,3.812463,2.341300,2.455264,8631.962088,1162.764369,7469.197719,108.713167,4404.391764,64.861841,66.579995,0.274901
std,3.689769e+07,8.016420,1.298956,7.986593,1.554440,1.010584,1.106267,9089.225428,815.012238,9091.132356,353.912795,3397.157925,23.471594,284.001363,0.275704
min,7.080821e+08,26.000000,0.000000,13.000000,1.000000,0.000000,0.000000,1438.300000,0.000000,3.000000,0.000000,510.000000,10.000000,0.000000,0.000000
25%,7.130365e+08,41.000000,1.000000,31.000000,3.000000,2.000000,2.000000,2555.000000,358.000000,1324.250000,0.631000,2156.000000,45.000000,0.582000,0.023000
50%,7.179256e+08,46.000000,2.000000,36.000000,4.000000,2.000000,2.000000,4549.000000,1276.000000,3473.000000,0.736000,3899.500000,67.000000,0.702000,0.175500
75%,7.731328e+08,52.000000,3.000000,40.000000,5.000000,3.000000,3.000000,11067.750000,1784.000000,9860.000000,0.859000,4741.000000,81.000000,0.818000,0.503000
max,8.283431e+08,73.000000,5.000000,56.000000,6.000000,6.000000,6.000000,34516.000000,2517.000000,34516.000000,3397.000000,18484.000000,139.000000,3714.000000,0.999000